version: "3"
services:
  app:
    build:
      context: ./docker
    volumes:
      - ./src:/usr/src/app
    ports:
      - 13000:3000
    command: sh -c "cd app && yarn start"
    working_dir: /usr/src/app
